- hosts: all
  become: true
  tasks:
     - name: Delete Old Deployment
       command: kubectl delete -f /opt/deployment.yaml --force

     - name: Delete Old Service
       command: kubectl delete -f /opt/service.yaml --force

     - name: create new Deployment
       command: kubectl apply -f /opt/deployment.yaml
    
     - name: create new Service
       command: kubectl apply -f /opt/service.yaml
    