apiVersion: v1
kind: Service
metadata:
  name: miss-simran
  labels:
    app: miss-simran
spec:
  ports:
    - port: 8080
      targetPort: 80
      nodePort: 31300
  selector:
    app: miss-simran
  type: LoadBalancer
